<?php

/**
 * @file
 * Contains email_management.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function email_management_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the email_management module.
    case 'help.page.email_management':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module used to manage transactional e-mail providers') . '</p>';
      return $output;

    default:
  }
}
