email_management.email_provider.*:
  type: config_entity
  label: 'Email provider config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    domain:
      type: string
      label: 'Domain Name'
    api_key:
      type: string
      label: 'API Key'
